# Generated by Django 5.2.15 on 2026-08-13 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='客户名')),
                ('phone', models.CharField(max_length=20, verbose_name='手机号码')),
                ('source', models.CharField(choices=[('web', '官网'), ('referral', '转介绍'), ('cold_call', '电话陌拜'), ('other', '其他')], max_length=20, verbose_name='来源')),
                ('note', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='填写时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL, verbose_name='外键')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
                'db_table': 'tb_client',
            },
        ),
    ]
